task "example" {
  driver = "docker"

  config {
    image = "secret/service"

    auth {
      username = "dockerhub_user"

      # ruleid: docker-hardcoded-password
      password = "dockerhub_password"
    }
  }
}

task "example" {
  driver = "docker"

  config {
    image = "secret/service"

    auth {
      username = "dockerhub_user"

      # ok: docker-hardcoded-password
      password = "${PASSWORD}"
    }
  }
}

task "example" {
  driver = "podman"

  config {
    image = "secret/service"

    auth {
      username = "dockerhub_user"

      # ruleid: docker-hardcoded-password
      password = "dockerhub_password"
    }
  }
}
