name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: auth
        name: Authenticate to GCP
        uses: google-github-actions/auth@v0.3.1
        # ruleid: gcp-credentials-json
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - id: auth
        name: Authenticate to GCP
        uses: "google-github-actions/auth@v0.3.1"
        # ruleid: gcp-credentials-json
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - id: auth
        name: Authenticate to GCP
        uses: google-github-actions/auth@v0.3.1
        # ok: gcp-credentials-json
        with:
          create_credentials_file: "true"
          workload_identity_provider: "<example-workload-identity-provider>"
          service_account: "<example-service-account>"
      - id: gcloud
        name: gcloud
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud services list
