name: Setup JFrog

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_USER: ${{ secrets.JF_USER }}
          # ruleid: jfrog-hardcoded-credential
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
          # ruleid: jfrog-hardcoded-credential
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          # ruleid: jfrog-hardcoded-credential
          JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
      - uses: "jfrog/setup-jfrog-cli@v4"
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_USER: ${{ secrets.JF_USER }}
          # ruleid: jfrog-hardcoded-credential
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
      - run: |
          jf rt ping
      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
        with:
          # ok: jfrog-hardcoded-credential
          oidc-provider-name: setup-jfrog-cli
      - run: |
          jf rt ping
