---
services:
  web:
    build: .
    ports:
      # ruleid: port-all-interfaces
      - "3000"
      # ruleid: port-all-interfaces
      - "3000-3005"
      # ruleid: port-all-interfaces
      - "8000:8000"
      # ruleid: port-all-interfaces
      - "9090-9091:8080-8081"
      # ruleid: port-all-interfaces
      - "49100:22"
      # ruleid: port-all-interfaces
      - "8000-9000:80"
      # ruleid: port-all-interfaces
      - "6060:6060/udp"
      # ok: port-all-interfaces
      - "127.0.0.1:8001:8001"
      # ok: port-all-interfaces
      - "127.0.0.2:8001:8001"
      # ok: port-all-interfaces
      - "127.255.255.255:8001:8001"
      # ok: port-all-interfaces
      - "127.0.0.1:5000-5010:5000-5010"
  redis:
    image: "redis:alpine"
