---
- name: Semgrep tests
  hosts: all
  tasks:
    - name: Positive test
      ansible.builtin.apt:
        # ruleid: apt-unencrypted-url
        deb: http://example.com/package.deb
    - name: Negative test
      ansible.builtin.apt:
        # ok: apt-unencrypted-url
        deb: https://example.com/package.deb
