rules:
  - id: dnf-validate-certs-disabled
    message: Found dnf with SSL verification disabled
    languages: [yaml]
    severity: WARNING
    metadata:
      category: security
      cwe: "CWE-295: Improper Certificate Validation"
      subcategory: [audit]
      technology: [ansible, dnf]
      confidence: HIGH
      likelihood: HIGH
      impact: HIGH
      references:
        - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf_module.html#parameter-validate_certs
        - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf5_module.html#parameter-validate_certs
    patterns:
      - pattern-inside: |
          $DNF:
            ...
      - metavariable-pattern:
          metavariable: $DNF
          pattern-either:
            - pattern: dnf
            - pattern: ansible.builtin.dnf
            - pattern: dnf5
            - pattern: ansible.builtin.dnf5
      - pattern: "$KEY: $VALUE"
      - metavariable-pattern:
          metavariable: $KEY
          pattern-either:
            - pattern: validate_certs
      - metavariable-pattern:
          metavariable: $VALUE
          pattern-either:
            - pattern: "false"
