---
- name: Semgrep tests
  hosts: all
  tasks:
    - name: Positive test
      ansible.builtin.get_url:
        # ruleid: get-url-unencrypted-url
        url: http://example.com/file.txt
        dest: /etc/file.txt
    - name: Positive test
      ansible.windows.win_get_url:
        # ruleid: get-url-unencrypted-url
        url: http://example.com/file.txt
        dest: C:\Users\ExampleUser\file.txt
    - name: Negative test
      ansible.builtin.get_url:
        # ok: get-url-unencrypted-url
        url: https://example.com/file.txt
        dest: /etc/file.txt
    - name: Negative test
      ansible.windows.win_get_url:
        # ok: get-url-unencrypted-url
        url: https://example.com/file.txt
        dest: C:\Users\ExampleUser\file.txt
    - name: Negative test
      ansible.builtin.get_url:
        # ok: get-url-unencrypted-url
        url: http://example.com/file.txt
        validate_certs: false
        dest: /etc/file.txt
        checksum: sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    - name: Negative test
      ansible.windows.win_get_url:
        # ok: get-url-unencrypted-url
        url: http://example.com/file.txt
        validate_certs: false
        dest: C:\Users\ExampleUser\file.txt
        checksum: sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
