rules:
  - id: rpm-key-validate-certs-disabled
    message: Found RPM key with SSL verification disabled
    languages: [yaml]
    severity: WARNING
    metadata:
      category: security
      cwe: "CWE-295: Improper Certificate Validation"
      subcategory: [audit]
      technology: [ansible, rpm]
      confidence: HIGH
      likelihood: HIGH
      impact: HIGH
      references:
        - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/rpm_key_module.html#parameter-validate_certs
    patterns:
      - pattern-inside: |
          $RPMKEY:
            ...
            key: ...
            ...
      - metavariable-pattern:
          metavariable: $RPMKEY
          pattern-either:
            - pattern: rpm_key
            - pattern: ansible.builtin.rpm_key
      - pattern: "$KEY: $VALUE"
      - metavariable-pattern:
          metavariable: $KEY
          pattern-either:
            - pattern: validate_certs
      - metavariable-pattern:
          metavariable: $VALUE
          pattern-either:
            - pattern: "false"
