rules:
  - id: rpm-key-unencrypted-url
    message: Found RPM key download with unencrypted URL (e.g. HTTP, FTP, etc.)
    languages: [yaml]
    severity: WARNING
    metadata:
      category: security
      cwe: "CWE-319: Cleartext Transmission of Sensitive Information"
      subcategory: [audit]
      technology: [ansible, rpm]
      confidence: HIGH
      likelihood: HIGH
      impact: HIGH
      references:
        - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/rpm_key_module.html#parameter-key
    patterns:
      - pattern-inside: |
          $RPMKEY:
            ...
      - metavariable-pattern:
          metavariable: $RPMKEY
          pattern-either:
            - pattern: rpm_key
            - pattern: ansible.builtin.rpm_key
      - pattern: "$KEY: '$VALUE'"
      - metavariable-pattern:
          metavariable: $KEY
          pattern-either:
            - pattern: key
      - metavariable-regex:
          metavariable: $VALUE
          regex: "(?i)^(http|ftp)://.*"
