rules:
  - id: unarchive-validate-certs-disabled
    message: Found unarchive download with SSL verification disabled
    languages: [yaml]
    severity: WARNING
    metadata:
      category: security
      cwe: "CWE-295: Improper Certificate Validation"
      subcategory: [audit]
      technology: [ansible]
      confidence: HIGH
      likelihood: HIGH
      impact: HIGH
      references:
        - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/unarchive_module.html#parameter-validate_certs
    patterns:
      - pattern-inside: |
          $UNARCHIVE:
            ...
      - metavariable-pattern:
          metavariable: $UNARCHIVE
          pattern-either:
            - pattern: unarchive
            - pattern: ansible.builtin.unarchive
      - pattern: "$KEY: $VALUE"
      - metavariable-pattern:
          metavariable: $KEY
          pattern-either:
            - pattern: validate_certs
      - metavariable-pattern:
          metavariable: $VALUE
          pattern-either:
            - pattern: "false"
