rules:
  - id: yum-unencrypted-url
    message: Found yum download with unencrypted URL (e.g. HTTP, FTP, etc.)
    languages: [yaml]
    severity: WARNING
    metadata:
      category: security
      cwe: "CWE-319: Cleartext Transmission of Sensitive Information"
      subcategory: [audit]
      technology: [ansible, yum]
      confidence: HIGH
      likelihood: HIGH
      impact: HIGH
      references:
        - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html#parameter-name
    patterns:
      - pattern-inside: |
          $YUM:
            ...
      - metavariable-pattern:
          metavariable: $YUM
          pattern-either:
            - pattern: yum
            - pattern: ansible.builtin.yum
      - pattern: "$KEY: '$VALUE'"
      - metavariable-pattern:
          metavariable: $KEY
          pattern-either:
            - pattern: name
            - pattern: pkg
      - metavariable-regex:
          metavariable: $VALUE
          regex: "(?i)^(http|ftp)://.*"
