name: update-semgrep-registry
on:
  push:
    branches:
      - main
jobs:
  update-semgrep-registry:
    name: Update semgrep.dev
    runs-on: ubuntu-latest
    steps:
      - name: update staging.semgrep.dev
        run: curl --fail -X POST -L https://staging.semgrep.dev/api/admin/update-registry?rule_type=sast
      - name: update semgrep.dev
        run: curl --fail -X POST -L https://semgrep.dev/api/admin/update-registry?rule_type=sast
